 export const consultationLanguages = [
  { name: "countries.Philippines", code: "PH", emoji: "🇵🇭", timezone: "UTC+8" },
  { name: "countries.Croatia", code: "HR", emoji: "🇭🇷", timezone: "UTC+1" },
  { name: "countries.Chad", code: "TD", emoji: "🇹🇩", timezone: "UTC+1" },
  { name: "countries.Czechia", code: "CZ", emoji: "🇨🇿", timezone: "UTC+1" },
  { name: "countries.Chile", code: "CL", emoji: "🇨🇱", timezone: "UTC-4" },
  { name: "countries.Montenegro", code: "ME", emoji: "🇲🇪", timezone: "UTC+1" },
  {
    name: "countries.Sri Lanka",
    code: "LK",
    emoji: "🇱🇰",
    timezone: "UTC+5:30",
  },
  { name: "countries.Jamaica", code: "JM", emoji: "🇯🇲", timezone: "UTC-5" },
  { name: "countries.Ukraine", code: "uk", emoji: "🇺🇦", timezone: "UTC+2" },
  {
    name: "countries.United Kingdom",
    code: "en",
    emoji: "🇬🇧",
    timezone: "UTC+0",
  },
  { name: "countries.United States", code: "US", emoji: "🇺🇸", timezone: "UTC-5" },
  { name: "countries.Canada", code: "CA", emoji: "🇨🇦", timezone: "UTC-6" },
  { name: "countries.Germany", code: "ge", emoji: "🇩🇪", timezone: "UTC+1" },
  { name: "countries.France", code: "FR", emoji: "🇫🇷", timezone: "UTC+1" },
  { name: "countries.Poland", code: "PL", emoji: "🇵🇱", timezone: "UTC+1" },
  { name: "countries.Italy", code: "IT", emoji: "🇮🇹", timezone: "UTC+1" },
  { name: "countries.Spain", code: "ES", emoji: "🇪🇸", timezone: "UTC+1" },
  { name: "countries.Japan", code: "JP", emoji: "🇯🇵", timezone: "UTC+9" },
  { name: "countries.China", code: "CN", emoji: "🇨🇳", timezone: "UTC+8" },
  { name: "countries.India", code: "IN", emoji: "🇮🇳", timezone: "UTC+5:30" },
  { name: "countries.Australia", code: "AU", emoji: "🇦🇺", timezone: "UTC+10" },
  { name: "countries.Brazil", code: "BR", emoji: "🇧🇷", timezone: "UTC-3" },
  { name: "countries.Turkey", code: "TR", emoji: "🇹🇷", timezone: "UTC+3" },
  { name: "countries.Sweden", code: "SE", emoji: "🇸🇪", timezone: "UTC+1" },
  { name: "countries.Switzerland", code: "CH", emoji: "🇨🇭", timezone: "UTC+1" },
  { name: "countries.Netherlands", code: "NL", emoji: "🇳🇱", timezone: "UTC+1" },
  { name: "countries.Norway", code: "NO", emoji: "🇳🇴", timezone: "UTC+1" },
  { name: "countries.Denmark", code: "DK", emoji: "🇩🇰", timezone: "UTC+1" },
  { name: "countries.Finland", code: "FI", emoji: "🇫🇮", timezone: "UTC+2" },
  {
    name: "countries.South Africa",
    code: "ZA",
    emoji: "🇿🇦",
    timezone: "UTC+2",
  },
  { name: "countries.Mexico", code: "MX", emoji: "🇲🇽", timezone: "UTC-6" },
  { name: "countries.South Korea", code: "KR", emoji: "🇰🇷", timezone: "UTC+9" },
  { name: "countries.Argentina", code: "AR", emoji: "🇦🇷", timezone: "UTC-3" },
  { name: "countries.Ireland", code: "IE", emoji: "🇮🇪", timezone: "UTC+0" },
  {
    name: "countries.New Zealand",
    code: "NZ",
    emoji: "🇳🇿",
    timezone: "UTC+12",
  },
  { name: "countries.Singapore", code: "SG", emoji: "🇸🇬", timezone: "UTC+8" },
  { name: "countries.Israel", code: "IL", emoji: "🇮🇱", timezone: "UTC+2" },
  { name: "countries.Malaysia", code: "MY", emoji: "🇲🇾", timezone: "UTC+8" },
  { name: "countries.Thailand", code: "TH", emoji: "🇹🇭", timezone: "UTC+7" },
  { name: "countries.Vietnam", code: "VN", emoji: "🇻🇳", timezone: "UTC+7" },
  { name: "countries.Indonesia", code: "ID", emoji: "🇮🇩", timezone: "UTC+8" },
  { name: "countries.Egypt", code: "EG", emoji: "🇪🇬", timezone: "UTC+2" },
  { name: "countries.Nigeria", code: "NG", emoji: "🇳🇬", timezone: "UTC+1" },
  {
    name: "countries.Saudi Arabia",
    code: "SA",
    emoji: "🇸🇦",
    timezone: "UTC+3",
  },
  {
    name: "countries.United Arab Emirates",
    code: "AE",
    emoji: "🇦🇪",
    timezone: "UTC+4",
  },
  { name: "countries.Kuwait", code: "KW", emoji: "🇰🇼", timezone: "UTC+3" },
  { name: "countries.Qatar", code: "QA", emoji: "🇶🇦", timezone: "UTC+3" },
  { name: "countries.Austria", code: "AT", emoji: "🇦🇹", timezone: "UTC+1" },
  { name: "countries.Azerbaijan", code: "AZ", emoji: "🇦🇿", timezone: "UTC+4" },
  { name: "countries.Albania", code: "AL", emoji: "🇦🇱", timezone: "UTC+1" },
  { name: "countries.Algeria", code: "DZ", emoji: "🇩🇿", timezone: "UTC+1" },
  { name: "countries.Angola", code: "AO", emoji: "🇦🇴", timezone: "UTC+1" },
  { name: "countries.Andorra", code: "AD", emoji: "🇦🇩", timezone: "UTC+1" },
  {
    name: "countries.Antigua and Barbuda",
    code: "AG",
    emoji: "🇦🇬",
    timezone: "UTC-4",
  },
  {
    name: "countries.Afghanistan",
    code: "AF",
    emoji: "🇦🇫",
    timezone: "UTC+4:30",
  },
  { name: "countries.Bahamas", code: "BS", emoji: "🇧🇸", timezone: "UTC-5" },
  { name: "countries.Bangladesh", code: "BD", emoji: "🇧🇩", timezone: "UTC+6" },
  { name: "countries.Barbados", code: "BB", emoji: "🇧🇧", timezone: "UTC-4" },
  { name: "countries.Bahrain", code: "BH", emoji: "🇧🇭", timezone: "UTC+3" },
  { name: "countries.Belize", code: "BZ", emoji: "🇧🇿", timezone: "UTC-6" },
  { name: "countries.Belgium", code: "BE", emoji: "🇧🇪", timezone: "UTC+1" },
  { name: "countries.Benin", code: "BJ", emoji: "🇧🇯", timezone: "UTC+1" },
  { name: "countries.Belarus", code: "BY", emoji: "🇧🇾", timezone: "UTC+3" },
  { name: "countries.Bulgaria", code: "BG", emoji: "🇧🇬", timezone: "UTC+2" },
  { name: "countries.Bolivia", code: "BO", emoji: "🇧🇴", timezone: "UTC-4" },
  {
    name: "countries.Bosnia and Herzegovina",
    code: "BA",
    emoji: "🇧🇦",
    timezone: "UTC+1",
  },
  { name: "countries.Botswana", code: "BW", emoji: "🇧🇼", timezone: "UTC+2" },
  { name: "countries.Brunei", code: "BN", emoji: "🇧🇳", timezone: "UTC+8" },
  {
    name: "countries.Burkina Faso",
    code: "BF",
    emoji: "🇧🇫",
    timezone: "UTC+0",
  },
  { name: "countries.Burundi", code: "BI", emoji: "🇧🇮", timezone: "UTC+2" },
  { name: "countries.Bhutan", code: "BT", emoji: "🇧🇹", timezone: "UTC+6" },
  { name: "countries.Vanuatu", code: "VU", emoji: "🇻🇺", timezone: "UTC+11" },
  { name: "countries.Venezuela", code: "VE", emoji: "🇻🇪", timezone: "UTC-4" },
  { name: "countries.Armenia", code: "AM", emoji: "🇦🇲", timezone: "UTC+4" },
  { name: "countries.Gabon", code: "GA", emoji: "🇬🇦", timezone: "UTC+1" },
  { name: "countries.Haiti", code: "HT", emoji: "🇭🇹", timezone: "UTC-5" },
  { name: "countries.Gambia", code: "GM", emoji: "🇬🇲", timezone: "UTC+0" },
  { name: "countries.Ghana", code: "GH", emoji: "🇬🇭", timezone: "UTC+0" },
  { name: "countries.Guyana", code: "GY", emoji: "🇬🇾", timezone: "UTC-4" },
  { name: "countries.Guatemala", code: "GT", emoji: "🇬🇹", timezone: "UTC-6" },
  { name: "countries.Guinea", code: "GN", emoji: "🇬🇳", timezone: "UTC+0" },
  {
    name: "countries.Guinea-Bissau",
    code: "GW",
    emoji: "🇬🇼",
    timezone: "UTC+0",
  },
  { name: "countries.Honduras", code: "HN", emoji: "🇭🇳", timezone: "UTC-6" },
  { name: "countries.Grenada", code: "GD", emoji: "🇬🇩", timezone: "UTC-4" },
  { name: "countries.Greece", code: "GR", emoji: "🇬🇷", timezone: "UTC+2" },
  { name: "countries.Georgia", code: "GE", emoji: "🇬🇪", timezone: "UTC+4" },
  { name: "countries.Djibouti", code: "DJ", emoji: "🇩🇯", timezone: "UTC+3" },
  { name: "countries.Dominica", code: "DM", emoji: "🇩🇲", timezone: "UTC-4" },
  {
    name: "countries.Dominican Republic",
    code: "DO",
    emoji: "🇩🇴",
    timezone: "UTC-4",
  },
  { name: "countries.DR Congo", code: "CD", emoji: "🇨🇩", timezone: "UTC+1" },
  { name: "countries.Ecuador", code: "EC", emoji: "🇪🇨", timezone: "UTC-5" },
  {
    name: "countries.Equatorial Guinea",
    code: "GQ",
    emoji: "🇬🇶",
    timezone: "UTC+1",
  },
  { name: "countries.Eritrea", code: "ER", emoji: "🇪🇷", timezone: "UTC+3" },
  { name: "countries.Eswatini", code: "SZ", emoji: "🇸🇿", timezone: "UTC+2" },
  { name: "countries.Estonia", code: "EE", emoji: "🇪🇪", timezone: "UTC+2" },
  { name: "countries.Ethiopia", code: "ET", emoji: "🇪🇹", timezone: "UTC+3" },
  { name: "countries.Yemen", code: "YE", emoji: "🇾🇪", timezone: "UTC+3" },
  { name: "countries.Zambia", code: "ZM", emoji: "🇿🇲", timezone: "UTC+2" },
  { name: "countries.Zimbabwe", code: "ZW", emoji: "🇿🇼", timezone: "UTC+2" },
  { name: "countries.Iran", code: "IR", emoji: "🇮🇷", timezone: "UTC+3:30" },
  { name: "countries.Iceland", code: "IS", emoji: "🇮🇸", timezone: "UTC+0" },
  { name: "countries.Iraq", code: "IQ", emoji: "🇮🇶", timezone: "UTC+3" },
  { name: "countries.Jordan", code: "JO", emoji: "🇯🇴", timezone: "UTC+2" },
  { name: "countries.Cape Verde", code: "CV", emoji: "🇨🇻", timezone: "UTC-1" },
  { name: "countries.Kazakhstan", code: "KZ", emoji: "🇰🇿", timezone: "UTC+5" },
  { name: "countries.Cambodia", code: "KH", emoji: "🇰🇭", timezone: "UTC+7" },
  { name: "countries.Cameroon", code: "CM", emoji: "🇨🇲", timezone: "UTC+1" },
  { name: "countries.Kenya", code: "KE", emoji: "🇰🇪", timezone: "UTC+3" },
  { name: "countries.Kyrgyzstan", code: "KG", emoji: "🇰🇬", timezone: "UTC+6" },
  { name: "countries.Cyprus", code: "CY", emoji: "🇨🇾", timezone: "UTC+2" },
  { name: "countries.Kiribati", code: "KI", emoji: "🇰🇮", timezone: "UTC+13" },
  { name: "countries.Colombia", code: "CO", emoji: "🇨🇴", timezone: "UTC-5" },
  { name: "countries.Comoros", code: "KM", emoji: "🇰🇲", timezone: "UTC+4" },
  { name: "countries.Costa Rica", code: "CR", emoji: "🇨🇷", timezone: "UTC-6" },
  { name: "countries.Ivory Coast", code: "CI", emoji: "🇨🇮", timezone: "UTC+0" },
  { name: "countries.Cuba", code: "CU", emoji: "🇨🇺", timezone: "UTC-5" },
  { name: "countries.Laos", code: "LA", emoji: "🇱🇦", timezone: "UTC+7" },
  { name: "countries.Latvia", code: "LV", emoji: "🇱🇻", timezone: "UTC+2" },
  { name: "countries.Lesotho", code: "LS", emoji: "🇱🇸", timezone: "UTC+2" },
  { name: "countries.Lithuania", code: "LT", emoji: "🇱🇹", timezone: "UTC+2" },
  { name: "countries.Liberia", code: "LR", emoji: "🇱🇷", timezone: "UTC+0" },
  { name: "countries.Lebanon", code: "LB", emoji: "🇱🇧", timezone: "UTC+2" },
  { name: "countries.Libya", code: "LY", emoji: "🇱🇾", timezone: "UTC+1" },
  {
    name: "countries.Liechtenstein",
    code: "LI",
    emoji: "🇱🇮",
    timezone: "UTC+1",
  },
  { name: "countries.Luxembourg", code: "LU", emoji: "🇱🇺", timezone: "UTC+1" },
  { name: "countries.Myanmar", code: "MM", emoji: "🇲🇲", timezone: "UTC+6:30" },
  { name: "countries.Mauritius", code: "MU", emoji: "🇲🇺", timezone: "UTC+4" },
  { name: "countries.Mauritania", code: "MR", emoji: "🇲🇷", timezone: "UTC+0" },
  {
    name: "countries.Madagascar",
    code: "MG",
    emoji: "🇲🇬",
    timezone: "UTC+3",
  },
  { name: "countries.Malawi", code: "MW", emoji: "🇲🇼", timezone: "UTC+2" },
  { name: "countries.Mali", code: "ML", emoji: "🇲🇱", timezone: "UTC+0" },
  { name: "countries.Maldives", code: "MV", emoji: "🇲🇻", timezone: "UTC+5" },
  { name: "countries.Malta", code: "MT", emoji: "🇲🇹", timezone: "UTC+1" },
  { name: "countries.Morocco", code: "MA", emoji: "🇲🇦", timezone: "UTC+1" },
  {
    name: "countries.Marshall Islands",
    code: "MH",
    emoji: "🇲🇭",
    timezone: "UTC+12",
  },
  { name: "countries.Mozambique", code: "MZ", emoji: "🇲🇿", timezone: "UTC+2" },
  { name: "countries.Moldova", code: "MD", emoji: "🇲🇩", timezone: "UTC+2" },
  { name: "countries.Monaco", code: "MC", emoji: "🇲🇨", timezone: "UTC+1" },
  { name: "countries.Mongolia", code: "MN", emoji: "🇲🇳", timezone: "UTC+8" },
  { name: "countries.Namibia", code: "NA", emoji: "🇳🇦", timezone: "UTC+1" },
  { name: "countries.Nauru", code: "NR", emoji: "🇳🇷", timezone: "UTC+12" },
  { name: "countries.Nepal", code: "NP", emoji: "🇳🇵", timezone: "UTC+5:45" },
  { name: "countries.Niger", code: "NE", emoji: "🇳🇪", timezone: "UTC+1" },
  { name: "countries.Nicaragua", code: "NI", emoji: "🇳🇮", timezone: "UTC-6" },
  { name: "countries.Oman", code: "OM", emoji: "🇴🇲", timezone: "UTC+4" },
  { name: "countries.Pakistan", code: "PK", emoji: "🇵🇰", timezone: "UTC+5" },
  { name: "countries.Palau", code: "PW", emoji: "🇵🇼", timezone: "UTC+9" },
  { name: "countries.Panama", code: "PA", emoji: "🇵🇦", timezone: "UTC-5" },
  {
    name: "countries.Papua New Guinea",
    code: "PG",
    emoji: "🇵🇬",
    timezone: "UTC+10",
  },
  { name: "countries.Paraguay", code: "PY", emoji: "🇵🇾", timezone: "UTC-4" },
  { name: "countries.Peru", code: "PE", emoji: "🇵🇪", timezone: "UTC-5" },
  { name: "countries.South Sudan", code: "SS", emoji: "🇸🇸", timezone: "UTC+2" },
  {
    name: "countries.North Korea",
    code: "KP",
    emoji: "🇰🇵",
    timezone: "UTC+8:30",
  },
  {
    name: "countries.North Macedonia",
    code: "MK",
    emoji: "🇲🇰",
    timezone: "UTC+1",
  },
  { name: "countries.Portugal", code: "PT", emoji: "🇵🇹", timezone: "UTC+0" },
  {
    name: "countries.Republic of the Congo",
    code: "CG",
    emoji: "🇨🇬",
    timezone: "UTC+1",
  },
  { name: "countries.Russia", code: "RU", emoji: "🇷🇺", timezone: "UTC+3" }, // Московський час
  { name: "countries.Rwanda", code: "RW", emoji: "🇷🇼", timezone: "UTC+2" },
  { name: "countries.Romania", code: "RO", emoji: "🇷🇴", timezone: "UTC+2" },
  { name: "countries.El Salvador", code: "SV", emoji: "🇸🇻", timezone: "UTC-6" },
  { name: "countries.Samoa", code: "WS", emoji: "🇼🇸", timezone: "UTC+13" },
  { name: "countries.San Marino", code: "SM", emoji: "🇸🇲", timezone: "UTC+1" },
  {
    name: "countries.Sao Tome and Principe",
    code: "ST",
    emoji: "🇸🇹",
    timezone: "UTC+0",
  },
  { name: "countries.Seychelles", code: "SC", emoji: "🇸🇨", timezone: "UTC+4" },
  { name: "countries.Senegal", code: "SN", emoji: "🇸🇳", timezone: "UTC+0" },
  {
    name: "countries.Saint Vincent and the Grenadines",
    code: "VC",
    emoji: "🇻🇨",
    timezone: "UTC-4",
  },
  {
    name: "countries.Saint Kitts and Nevis",
    code: "KN",
    emoji: "🇰🇳",
    timezone: "UTC-4",
  },
  {
    name: "countries.Saint Lucia",
    code: "LC",
    emoji: "🇱🇨",
    timezone: "UTC-4",
  },
  { name: "countries.Serbia", code: "RS", emoji: "🇷🇸", timezone: "UTC+1" },
  { name: "countries.Syria", code: "SY", emoji: "🇸🇾", timezone: "UTC+2" },
  { name: "countries.Slovakia", code: "SK", emoji: "🇸🇰", timezone: "UTC+1" },
  { name: "countries.Slovenia", code: "SI", emoji: "🇸🇮", timezone: "UTC+1" },
  {
    name: "countries.Solomon Islands",
    code: "SB",
    emoji: "🇸🇧",
    timezone: "UTC+11",
  },
  { name: "countries.Somalia", code: "SO", emoji: "🇸🇴", timezone: "UTC+3" },
  { name: "countries.Sudan", code: "SD", emoji: "🇸🇩", timezone: "UTC+2" },
  { name: "countries.Suriname", code: "SR", emoji: "🇸🇷", timezone: "UTC-3" },
  { name: "countries.East Timor", code: "TL", emoji: "🇹🇱", timezone: "UTC+9" },
  {
    name: "countries.Sierra Leone",
    code: "SL",
    emoji: "🇸🇱",
    timezone: "UTC+0",
  },
  { name: "countries.Tajikistan", code: "TJ", emoji: "🇹🇯", timezone: "UTC+5" },
  { name: "countries.Tanzania", code: "TZ", emoji: "🇹🇿", timezone: "UTC+3" },
  { name: "countries.Togo", code: "TG", emoji: "🇹🇬", timezone: "UTC+0" },
  { name: "countries.Tonga", code: "TO", emoji: "🇹🇴", timezone: "UTC+13" },
  {
    name: "countries.Trinidad and Tobago",
    code: "TT",
    emoji: "🇹🇹",
    timezone: "UTC-5",
  },
  { name: "countries.Tuvalu", code: "TV", emoji: "🇹🇻", timezone: "UTC+12" },
  { name: "countries.Tunisia", code: "TN", emoji: "🇹🇳", timezone: "UTC+1" },
  {
    name: "countries.Turkmenistan",
    code: "TM",
    emoji: "🇹🇲",
    timezone: "UTC+5",
  },
  { name: "countries.Uganda", code: "UG", emoji: "🇺🇬", timezone: "UTC+3" },
  { name: "countries.Hungary", code: "HU", emoji: "🇭🇺", timezone: "UTC+1" },
  { name: "countries.Uzbekistan", code: "UZ", emoji: "🇺🇿", timezone: "UTC+5" },
  { name: "countries.Uruguay", code: "UY", emoji: "🇺🇾", timezone: "UTC-3" },
  {
    name: "countries.Federated States of Micronesia",
    code: "FM",
    emoji: "🇫🇲",
    timezone: "UTC+10",
  },
  { name: "countries.Fiji", code: "FJ", emoji: "🇫🇯", timezone: "UTC+12" },
  {
    name: "countries.Central African Republic",
    code: "CF",
    emoji: "🇨🇫",
    timezone: "UTC+1",
  },
];