export const countries = [
  { name: "Ukraine", code: "UA", emoji: "🇺🇦", timezone: "UTC+2", ianaTimezone: "Europe/Kiev" },
  { name: "United Kingdom", code: "GB", emoji: "🇬🇧", timezone: "UTC+0", ianaTimezone: "Europe/London" },
  { name: "United States", code: "US", emoji: "🇺🇸", timezone: "UTC-5", ianaTimezone: "America/New_York" },
  { name: "Canada", code: "CA", emoji: "🇨🇦", timezone: "UTC-6", ianaTimezone: "America/Toronto" },
  { name: "Germany", code: "DE", emoji: "🇩🇪", timezone: "UTC+1", ianaTimezone: "Europe/Berlin" },
  { name: "France", code: "FR", emoji: "🇫🇷", timezone: "UTC+1", ianaTimezone: "Europe/Paris" },
  { name: "Poland", code: "PL", emoji: "🇵🇱", timezone: "UTC+1", ianaTimezone: "Europe/Warsaw" },
  { name: "Italy", code: "IT", emoji: "🇮🇹", timezone: "UTC+1", ianaTimezone: "Europe/Rome" },
  { name: "Spain", code: "ES", emoji: "🇪🇸", timezone: "UTC+1", ianaTimezone: "Europe/Madrid" },
  { name: "Japan", code: "JP", emoji: "🇯🇵", timezone: "UTC+9", ianaTimezone: "Asia/Tokyo" },
  { name: "China", code: "CN", emoji: "🇨🇳", timezone: "UTC+8", ianaTimezone: "Asia/Shanghai" },
  { name: "India", code: "IN", emoji: "🇮🇳", timezone: "UTC+5:30", ianaTimezone: "Asia/Kolkata" },
  { name: "Australia", code: "AU", emoji: "🇦🇺", timezone: "UTC+10", ianaTimezone: "Australia/Sydney" },
  { name: "Brazil", code: "BR", emoji: "🇧🇷", timezone: "UTC-3", ianaTimezone: "America/Sao_Paulo" },
  { name: "Turkey", code: "TR", emoji: "🇹🇷", timezone: "UTC+3", ianaTimezone: "Europe/Istanbul" },
  { name: "Sweden", code: "SE", emoji: "🇸🇪", timezone: "UTC+1", ianaTimezone: "Europe/Stockholm" },
  { name: "Switzerland", code: "CH", emoji: "🇨🇭", timezone: "UTC+1", ianaTimezone: "Europe/Zurich" },
  { name: "Netherlands", code: "NL", emoji: "🇳🇱", timezone: "UTC+1", ianaTimezone: "Europe/Amsterdam" },
  { name: "Norway", code: "NO", emoji: "🇳🇴", timezone: "UTC+1", ianaTimezone: "Europe/Oslo" },
  { name: "Denmark", code: "DK", emoji: "🇩🇰", timezone: "UTC+1", ianaTimezone: "Europe/Copenhagen" },
  { name: "Finland", code: "FI", emoji: "🇫🇮", timezone: "UTC+2", ianaTimezone: "Europe/Helsinki" },
  { name: "South Africa", code: "ZA", emoji: "🇿🇦", timezone: "UTC+2", ianaTimezone: "Africa/Johannesburg" },
  { name: "Mexico", code: "MX", emoji: "🇲🇽", timezone: "UTC-6", ianaTimezone: "America/Mexico_City" },
  { name: "South Korea", code: "KR", emoji: "🇰🇷", timezone: "UTC+9", ianaTimezone: "Asia/Seoul" },
  { name: "Argentina", code: "AR", emoji: "🇦🇷", timezone: "UTC-3", ianaTimezone: "America/Argentina/Buenos_Aires" },
  { name: "Ireland", code: "IE", emoji: "🇮🇪", timezone: "UTC+0", ianaTimezone: "Europe/Dublin" },
  { name: "New Zealand", code: "NZ", emoji: "🇳🇿", timezone: "UTC+12", ianaTimezone: "Pacific/Auckland" },
  { name: "Singapore", code: "SG", emoji: "🇸🇬", timezone: "UTC+8", ianaTimezone: "Asia/Singapore" },
  { name: "Israel", code: "IL", emoji: "🇮🇱", timezone: "UTC+2", ianaTimezone: "Asia/Jerusalem" },
  { name: "Malaysia", code: "MY", emoji: "🇲🇾", timezone: "UTC+8", ianaTimezone: "Asia/Kuala_Lumpur" },
  { name: "Thailand", code: "TH", emoji: "🇹🇭", timezone: "UTC+7", ianaTimezone: "Asia/Bangkok" },
  { name: "Vietnam", code: "VN", emoji: "🇻🇳", timezone: "UTC+7", ianaTimezone: "Asia/Ho_Chi_Minh" },
  { name: "Indonesia", code: "ID", emoji: "🇮🇩", timezone: "UTC+8", ianaTimezone: "Asia/Jakarta" },
  { name: "Egypt", code: "EG", emoji: "🇪🇬", timezone: "UTC+2", ianaTimezone: "Africa/Cairo" },
  { name: "Nigeria", code: "NG", emoji: "🇳🇬", timezone: "UTC+1", ianaTimezone: "Africa/Lagos" },
  { name: "Saudi Arabia", code: "SA", emoji: "🇸🇦", timezone: "UTC+3", ianaTimezone: "Asia/Riyadh" },
  { name: "United Arab Emirates", code: "AE", emoji: "🇦🇪", timezone: "UTC+4", ianaTimezone: "Asia/Dubai" },
  { name: "Kuwait", code: "KW", emoji: "🇰🇼", timezone: "UTC+3", ianaTimezone: "Asia/Kuwait" },
  { name: "Qatar", code: "QA", emoji: "🇶🇦", timezone: "UTC+3", ianaTimezone: "Asia/Qatar" },
  { name: "Austria", code: "AT", emoji: "🇦🇹", timezone: "UTC+1", ianaTimezone: "Europe/Vienna" },
  { name: "Azerbaijan", code: "AZ", emoji: "🇦🇿", timezone: "UTC+4", ianaTimezone: "Asia/Baku" },
  { name: "Albania", code: "AL", emoji: "🇦🇱", timezone: "UTC+1", ianaTimezone: "Europe/Tirane" },
  { name: "Algeria", code: "DZ", emoji: "🇩🇿", timezone: "UTC+1", ianaTimezone: "Africa/Algiers" },
  { name: "Angola", code: "AO", emoji: "🇦🇴", timezone: "UTC+1", ianaTimezone: "Africa/Luanda" },
  { name: "Andorra", code: "AD", emoji: "🇦🇩", timezone: "UTC+1", ianaTimezone: "Europe/Andorra" },
  { name: "Antigua and Barbuda", code: "AG", emoji: "🇦🇬", timezone: "UTC-4", ianaTimezone: "America/Antigua" },
  { name: "Afghanistan", code: "AF", emoji: "🇦🇫", timezone: "UTC+4:30", ianaTimezone: "Asia/Kabul" },
  { name: "Bahamas", code: "BS", emoji: "🇧🇸", timezone: "UTC-5", ianaTimezone: "America/Nassau" },
  { name: "Bangladesh", code: "BD", emoji: "🇧🇩", timezone: "UTC+6", ianaTimezone: "Asia/Dhaka" },
  { name: "Barbados", code: "BB", emoji: "🇧🇧", timezone: "UTC-4", ianaTimezone: "America/Barbados" },
  { name: "Bahrain", code: "BH", emoji: "🇧🇭", timezone: "UTC+3", ianaTimezone: "Asia/Bahrain" },
  { name: "Belize", code: "BZ", emoji: "🇧🇿", timezone: "UTC-6", ianaTimezone: "America/Belize" },
  { name: "Belgium", code: "BE", emoji: "🇧🇪", timezone: "UTC+1", ianaTimezone: "Europe/Brussels" },
  { name: "Benin", code: "BJ", emoji: "🇧🇯", timezone: "UTC+1", ianaTimezone: "Africa/Porto-Novo" },
  { name: "Belarus", code: "BY", emoji: "🇧🇾", timezone: "UTC+3", ianaTimezone: "Europe/Minsk" },
  { name: "Bulgaria", code: "BG", emoji: "🇧🇬", timezone: "UTC+2", ianaTimezone: "Europe/Sofia" },
  { name: "Bolivia", code: "BO", emoji: "🇧🇴", timezone: "UTC-4", ianaTimezone: "America/La_Paz" },
  { name: "Bosnia and Herzegovina", code: "BA", emoji: "🇧🇦", timezone: "UTC+1", ianaTimezone: "Europe/Sarajevo" },
  { name: "Botswana", code: "BW", emoji: "🇧🇼", timezone: "UTC+2", ianaTimezone: "Africa/Gaborone" },
  { name: "Brunei", code: "BN", emoji: "🇧🇳", timezone: "UTC+8", ianaTimezone: "Asia/Brunei" },
  { name: "Burkina Faso", code: "BF", emoji: "🇧🇫", timezone: "UTC+0", ianaTimezone: "Africa/Ouagadougou" },
  { name: "Burundi", code: "BI", emoji: "🇧🇮", timezone: "UTC+2", ianaTimezone: "Africa/Bujumbura" },
  { name: "Bhutan", code: "BT", emoji: "🇧🇹", timezone: "UTC+6", ianaTimezone: "Asia/Thimphu" },
  { name: "Vanuatu", code: "VU", emoji: "🇻🇺", timezone: "UTC+11", ianaTimezone: "Pacific/Efate" },
  { name: "Venezuela", code: "VE", emoji: "🇻🇪", timezone: "UTC-4", ianaTimezone: "America/Caracas" },
  { name: "Armenia", code: "AM", emoji: "🇦🇲", timezone: "UTC+4", ianaTimezone: "Asia/Yerevan" },
  { name: "Gabon", code: "GA", emoji: "🇬🇦", timezone: "UTC+1", ianaTimezone: "Africa/Libreville" },
  { name: "Haiti", code: "HT", emoji: "🇭🇹", timezone: "UTC-5", ianaTimezone: "America/Port-au-Prince" },
  { name: "Gambia", code: "GM", emoji: "🇬🇲", timezone: "UTC+0", ianaTimezone: "Africa/Banjul" },
  { name: "Ghana", code: "GH", emoji: "🇬🇭", timezone: "UTC+0", ianaTimezone: "Africa/Accra" },
  { name: "Guyana", code: "GY", emoji: "🇬🇾", timezone: "UTC-4", ianaTimezone: "America/Guyana" },
  { name: "Guatemala", code: "GT", emoji: "🇬🇹", timezone: "UTC-6", ianaTimezone: "America/Guatemala" },
  { name: "Guinea", code: "GN", emoji: "🇬🇳", timezone: "UTC+0", ianaTimezone: "Africa/Conakry" },
  { name: "Guinea-Bissau", code: "GW", emoji: "🇬🇼", timezone: "UTC+0", ianaTimezone: "Africa/Bissau" },
  { name: "Honduras", code: "HN", emoji: "🇭🇳", timezone: "UTC-6", ianaTimezone: "America/Tegucigalpa" },
  { name: "Grenada", code: "GD", emoji: "🇬🇩", timezone: "UTC-4", ianaTimezone: "America/Grenada" },
  { name: "Greece", code: "GR", emoji: "🇬🇷", timezone: "UTC+2", ianaTimezone: "Europe/Athens" },
  { name: "Georgia", code: "GE", emoji: "🇬🇪", timezone: "UTC+4", ianaTimezone: "Asia/Tbilisi" },
  { name: "Djibouti", code: "DJ", emoji: "🇩🇯", timezone: "UTC+3", ianaTimezone: "Africa/Djibouti" },
  { name: "Dominica", code: "DM", emoji: "🇩🇲", timezone: "UTC-4", ianaTimezone: "America/Dominica" },
  { name: "Dominican Republic", code: "DO", emoji: "🇩🇴", timezone: "UTC-4", ianaTimezone: "America/Santo_Domingo" },
  { name: "DR Congo", code: "CD", emoji: "🇨🇩", timezone: "UTC+1", ianaTimezone: "Africa/Kinshasa" },
  { name: "Ecuador", code: "EC", emoji: "🇪🇨", timezone: "UTC-5", ianaTimezone: "America/Guayaquil" },
  { name: "Equatorial Guinea", code: "GQ", emoji: "🇬🇶", timezone: "UTC+1", ianaTimezone: "Africa/Malabo" },
  { name: "Eritrea", code: "ER", emoji: "🇪🇷", timezone: "UTC+3", ianaTimezone: "Africa/Asmara" },
  { name: "Eswatini", code: "SZ", emoji: "🇸🇿", timezone: "UTC+2", ianaTimezone: "Africa/Mbabane" },
  { name: "Estonia", code: "EE", emoji: "🇪🇪", timezone: "UTC+2", ianaTimezone: "Europe/Tallinn" },
  { name: "Ethiopia", code: "ET", emoji: "🇪🇹", timezone: "UTC+3", ianaTimezone: "Africa/Addis_Ababa" },
  { name: "Yemen", code: "YE", emoji: "🇾🇪", timezone: "UTC+3", ianaTimezone: "Asia/Aden" },
  { name: "Zambia", code: "ZM", emoji: "🇿🇲", timezone: "UTC+2", ianaTimezone: "Africa/Lusaka" },
  { name: "Zimbabwe", code: "ZW", emoji: "🇿🇼", timezone: "UTC+2", ianaTimezone: "Africa/Harare" },
  { name: "Iran", code: "IR", emoji: "🇮🇷", timezone: "UTC+3:30", ianaTimezone: "Asia/Tehran" },
  { name: "Iceland", code: "IS", emoji: "🇮🇸", timezone: "UTC+0", ianaTimezone: "Atlantic/Reykjavik" },
  { name: "Iraq", code: "IQ", emoji: "🇮🇶", timezone: "UTC+3", ianaTimezone: "Asia/Baghdad" },
  { name: "Jordan", code: "JO", emoji: "🇯🇴", timezone: "UTC+2", ianaTimezone: "Asia/Amman" },
  { name: "Cape Verde", code: "CV", emoji: "🇨🇻", timezone: "UTC-1", ianaTimezone: "Atlantic/Cape_Verde" },
  { name: "Kazakhstan", code: "KZ", emoji: "🇰🇿", timezone: "UTC+5", ianaTimezone: "Asia/Almaty" },
  { name: "Cambodia", code: "KH", emoji: "🇰🇭", timezone: "UTC+7", ianaTimezone: "Asia/Phnom_Penh" },
  { name: "Cameroon", code: "CM", emoji: "🇨🇲", timezone: "UTC+1", ianaTimezone: "Africa/Douala" },
  { name: "Kenya", code: "KE", emoji: "🇰🇪", timezone: "UTC+3", ianaTimezone: "Africa/Nairobi" },
  { name: "Kyrgyzstan", code: "KG", emoji: "🇰🇬", timezone: "UTC+6", ianaTimezone: "Asia/Bishkek" },
  { name: "Cyprus", code: "CY", emoji: "🇨🇾", timezone: "UTC+2", ianaTimezone: "Asia/Nicosia" },
  { name: "Kiribati", code: "KI", emoji: "🇰🇮", timezone: "UTC+13", ianaTimezone: "Pacific/Kiritimati" },
  { name: "Colombia", code: "CO", emoji: "🇨🇴", timezone: "UTC-5", ianaTimezone: "America/Bogota" },
  { name: "Comoros", code: "KM", emoji: "🇰🇲", timezone: "UTC+4", ianaTimezone: "Indian/Comoro" },
  { name: "Costa Rica", code: "CR", emoji: "🇨🇷", timezone: "UTC-6", ianaTimezone: "America/Costa_Rica" },
  { name: "Ivory Coast", code: "CI", emoji: "🇨🇮", timezone: "UTC+0", ianaTimezone: "Africa/Abidjan" },
  { name: "Cuba", code: "CU", emoji: "🇨🇺", timezone: "UTC-5", ianaTimezone: "America/Havana" },
  { name: "Laos", code: "LA", emoji: "🇱🇦", timezone: "UTC+7", ianaTimezone: "Asia/Vientiane" },
  { name: "Latvia", code: "LV", emoji: "🇱🇻", timezone: "UTC+2", ianaTimezone: "Europe/Riga" },
  { name: "Lesotho", code: "LS", emoji: "🇱🇸", timezone: "UTC+2", ianaTimezone: "Africa/Maseru" },
  { name: "Lithuania", code: "LT", emoji: "🇱🇹", timezone: "UTC+2", ianaTimezone: "Europe/Vilnius" },
  { name: "Liberia", code: "LR", emoji: "🇱🇷", timezone: "UTC+0", ianaTimezone: "Africa/Monrovia" },
  { name: "Lebanon", code: "LB", emoji: "🇱🇧", timezone: "UTC+2", ianaTimezone: "Asia/Beirut" },
  { name: "Libya", code: "LY", emoji: "🇱🇾", timezone: "UTC+1", ianaTimezone: "Africa/Tripoli" },
  { name: "Liechtenstein", code: "LI", emoji: "🇱🇮", timezone: "UTC+1", ianaTimezone: "Europe/Vaduz" },
  { name: "Luxembourg", code: "LU", emoji: "🇱🇺", timezone: "UTC+1", ianaTimezone: "Europe/Luxembourg" },
  { name: "Myanmar", code: "MM", emoji: "🇲🇲", timezone: "UTC+6:30", ianaTimezone: "Asia/Yangon" },
  { name: "Mauritius", code: "MU", emoji: "🇲🇺", timezone: "UTC+4", ianaTimezone: "Indian/Mauritius" },
  { name: "Mauritania", code: "MR", emoji: "🇲🇷", timezone: "UTC+0", ianaTimezone: "Africa/Nouakchott" },
  { name: "Madagascar", code: "MG", emoji: "🇲🇬", timezone: "UTC+3", ianaTimezone: "Indian/Antananarivo" },
  { name: "Malawi", code: "MW", emoji: "🇲🇼", timezone: "UTC+2", ianaTimezone: "Africa/Blantyre" },
  { name: "Mali", code: "ML", emoji: "🇲🇱", timezone: "UTC+0", ianaTimezone: "Africa/Bamako" },
  { name: "Maldives", code: "MV", emoji: "🇲🇻", timezone: "UTC+5", ianaTimezone: "Indian/Maldives" },
  { name: "Malta", code: "MT", emoji: "🇲🇹", timezone: "UTC+1", ianaTimezone: "Europe/Malta" },
  { name: "Morocco", code: "MA", emoji: "🇲🇦", timezone: "UTC+1", ianaTimezone: "Africa/Casablanca" },
  { name: "Marshall Islands", code: "MH", emoji: "🇲🇭", timezone: "UTC+12", ianaTimezone: "Pacific/Majuro" },
  { name: "Mozambique", code: "MZ", emoji: "🇲🇿", timezone: "UTC+2", ianaTimezone: "Africa/Maputo" },
  { name: "Moldova", code: "MD", emoji: "🇲🇩", timezone: "UTC+2", ianaTimezone: "Europe/Chisinau" },
  { name: "Monaco", code: "MC", emoji: "🇲🇨", timezone: "UTC+1", ianaTimezone: "Europe/Monaco" },
  { name: "Mongolia", code: "MN", emoji: "🇲🇳", timezone: "UTC+8", ianaTimezone: "Asia/Ulaanbaatar" },
  { name: "Namibia", code: "NA", emoji: "🇳🇦", timezone: "UTC+1", ianaTimezone: "Africa/Windhoek" },
  { name: "Nauru", code: "NR", emoji: "🇳🇷", timezone: "UTC+12", ianaTimezone: "Pacific/Nauru" },
  { name: "Nepal", code: "NP", emoji: "🇳🇵", timezone: "UTC+5:45", ianaTimezone: "Asia/Kathmandu" },
  { name: "Niger", code: "NE", emoji: "🇳🇪", timezone: "UTC+1", ianaTimezone: "Africa/Niamey" },
  { name: "Nicaragua", code: "NI", emoji: "🇳🇮", timezone: "UTC-6", ianaTimezone: "America/Managua" },
  { name: "Oman", code: "OM", emoji: "🇴🇲", timezone: "UTC+4", ianaTimezone: "Asia/Muscat" },
  { name: "Pakistan", code: "PK", emoji: "🇵🇰", timezone: "UTC+5", ianaTimezone: "Asia/Karachi" },
  { name: "Palau", code: "PW", emoji: "🇵🇼", timezone: "UTC+9", ianaTimezone: "Pacific/Palau" },
  { name: "Panama", code: "PA", emoji: "🇵🇦", timezone: "UTC-5", ianaTimezone: "America/Panama" },
  { name: "Papua New Guinea", code: "PG", emoji: "🇵🇬", timezone: "UTC+10", ianaTimezone: "Pacific/Port_Moresby" },
  { name: "Paraguay", code: "PY", emoji: "🇵🇾", timezone: "UTC-4", ianaTimezone: "America/Asuncion" },
  { name: "Peru", code: "PE", emoji: "🇵🇪", timezone: "UTC-5", ianaTimezone: "America/Lima" },
  { name: "South Sudan", code: "SS", emoji: "🇸🇸", timezone: "UTC+2", ianaTimezone: "Africa/Juba" },
  { name: "North Korea", code: "KP", emoji: "🇰🇵", timezone: "UTC+8:30", ianaTimezone: "Asia/Pyongyang" },
  { name: "North Macedonia", code: "MK", emoji: "🇲🇰", timezone: "UTC+1", ianaTimezone: "Europe/Skopje" },
  { name: "Portugal", code: "PT", emoji: "🇵🇹", timezone: "UTC+0", ianaTimezone: "Europe/Lisbon" },
  { name: "Republic of the Congo", code: "CG", emoji: "🇨🇬", timezone: "UTC+1", ianaTimezone: "Africa/Brazzaville" },
  { name: "Russia", code: "RU", emoji: "🇷🇺", timezone: "UTC+3", ianaTimezone: "Europe/Moscow" },
  { name: "Rwanda", code: "RW", emoji: "🇷🇼", timezone: "UTC+2", ianaTimezone: "Africa/Kigali" },
  { name: "Romania", code: "RO", emoji: "🇷🇴", timezone: "UTC+2", ianaTimezone: "Europe/Bucharest" },
  { name: "El Salvador", code: "SV", emoji: "🇸🇻", timezone: "UTC-6", ianaTimezone: "America/El_Salvador" },
  { name: "Samoa", code: "WS", emoji: "🇼🇸", timezone: "UTC+13", ianaTimezone: "Pacific/Apia" },
  { name: "San Marino", code: "SM", emoji: "🇸🇲", timezone: "UTC+1", ianaTimezone: "Europe/San_Marino" },
  { name: "Sao Tome and Principe", code: "ST", emoji: "🇸🇹", timezone: "UTC+0", ianaTimezone: "Africa/Sao_Tome" },
  { name: "Seychelles", code: "SC", emoji: "🇸🇨", timezone: "UTC+4", ianaTimezone: "Indian/Mahe" },
  { name: "Senegal", code: "SN", emoji: "🇸🇳", timezone: "UTC+0", ianaTimezone: "Africa/Dakar" },
  { name: "Saint Vincent and the Grenadines", code: "VC", emoji: "🇻🇨", timezone: "UTC-4", ianaTimezone: "America/St_Vincent" },
  { name: "Saint Kitts and Nevis", code: "KN", emoji: "🇰🇳", timezone: "UTC-4", ianaTimezone: "America/St_Kitts" },
  { name: "Saint Lucia", code: "LC", emoji: "🇱🇨", timezone: "UTC-4", ianaTimezone: "America/St_Lucia" },
  { name: "Serbia", code: "RS", emoji: "🇷🇸", timezone: "UTC+1", ianaTimezone: "Europe/Belgrade" },
  { name: "Syria", code: "SY", emoji: "🇸🇾", timezone: "UTC+2", ianaTimezone: "Asia/Damascus" },
  { name: "Slovakia", code: "SK", emoji: "🇸🇰", timezone: "UTC+1", ianaTimezone: "Europe/Bratislava" },
  { name: "Slovenia", code: "SI", emoji: "🇸🇮", timezone: "UTC+1", ianaTimezone: "Europe/Ljubljana" },
  { name: "Solomon Islands", code: "SB", emoji: "🇸🇧", timezone: "UTC+11", ianaTimezone: "Pacific/Guadalcanal" },
  { name: "Somalia", code: "SO", emoji: "🇸🇴", timezone: "UTC+3", ianaTimezone: "Africa/Mogadishu" },
  { name: "Sudan", code: "SD", emoji: "🇸🇩", timezone: "UTC+2", ianaTimezone: "Africa/Khartoum" },
  { name: "Suriname", code: "SR", emoji: "🇸🇷", timezone: "UTC-3", ianaTimezone: "America/Paramaribo" },
  { name: "East Timor", code: "TL", emoji: "🇹🇱", timezone: "UTC+9", ianaTimezone: "Asia/Dili" },
  { name: "Sierra Leone", code: "SL", emoji: "🇸🇱", timezone: "UTC+0", ianaTimezone: "Africa/Freetown" },
  { name: "Tajikistan", code: "TJ", emoji: "🇹🇯", timezone: "UTC+5", ianaTimezone: "Asia/Dushanbe" },
  { name: "Tanzania", code: "TZ", emoji: "🇹🇿", timezone: "UTC+3", ianaTimezone: "Africa/Dar_es_Salaam" },
  { name: "Togo", code: "TG", emoji: "🇹🇬", timezone: "UTC+0", ianaTimezone: "Africa/Lome" },
  { name: "Tonga", code: "TO", emoji: "🇹🇴", timezone: "UTC+13", ianaTimezone: "Pacific/Tongatapu" },
  { name: "Trinidad and Tobago", code: "TT", emoji: "🇹🇹", timezone: "UTC-5", ianaTimezone: "America/Port_of_Spain" },
  { name: "Tuvalu", code: "TV", emoji: "🇹🇻", timezone: "UTC+12", ianaTimezone: "Pacific/Funafuti" },
  { name: "Tunisia", code: "TN", emoji: "🇹🇳", timezone: "UTC+1", ianaTimezone: "Africa/Tunis" },
  { name: "Turkmenistan", code: "TM", emoji: "🇹🇲", timezone: "UTC+5", ianaTimezone: "Asia/Ashgabat" },
  { name: "Uganda", code: "UG", emoji: "🇺🇬", timezone: "UTC+3", ianaTimezone: "Africa/Kampala" },
  { name: "Hungary", code: "HU", emoji: "🇭🇺", timezone: "UTC+1", ianaTimezone: "Europe/Budapest" },
  { name: "Uzbekistan", code: "UZ", emoji: "🇺🇿", timezone: "UTC+5", ianaTimezone: "Asia/Tashkent" },
  { name: "Uruguay", code: "UY", emoji: "🇺🇾", timezone: "UTC-3", ianaTimezone: "America/Montevideo" },
  { name: "Federated States of Micronesia", code: "FM", emoji: "🇫🇲", timezone: "UTC+10", ianaTimezone: "Pacific/Ponape" },
  { name: "Fiji", code: "FJ", emoji: "🇫🇯", timezone: "UTC+12", ianaTimezone: "Pacific/Fiji" },
  { name: "Philippines", code: "PH", emoji: "🇵🇭", timezone: "UTC+8", ianaTimezone: "Asia/Manila" },
  { name: "Croatia", code: "HR", emoji: "🇭🇷", timezone: "UTC+1", ianaTimezone: "Europe/Zagreb" },
  { name: "Central African Republic", code: "CF", emoji: "🇨🇫", timezone: "UTC+1", ianaTimezone: "Africa/Bangui" },
  { name: "Chad", code: "TD", emoji: "🇹🇩", timezone: "UTC+1", ianaTimezone: "Africa/Ndjamena" },
  { name: "Czechia", code: "CZ", emoji: "🇨🇿", timezone: "UTC+1", ianaTimezone: "Europe/Prague" },
  { name: "Chile", code: "CL", emoji: "🇨🇱", timezone: "UTC-4", ianaTimezone: "America/Santiago" },
  { name: "Montenegro", code: "ME", emoji: "🇲🇪", timezone: "UTC+1", ianaTimezone: "Europe/Podgorica" },
  { name: "Sri Lanka", code: "LK", emoji: "🇱🇰", timezone: "UTC+5:30", ianaTimezone: "Asia/Colombo" },
  { name: "Jamaica", code: "JM", emoji: "🇯🇲", timezone: "UTC-5", ianaTimezone: "America/Jamaica" },
];